### ISSUE TITLE
It is possible to debug with SWD instead of Jtag

### ISSUE THREAD

**Issue by PMLSTaisen** [bouffalolab/bl_mcu_sdk#104]
For BL702 chip, I have very limited GPIO pins, however, if I would like to use CV-Debugger, it takes me almost 4 pins for debugger, and another two UART for reading the print out, any way to make SWD (only 2 pins) as default debug protocol and Sipeed USBSTIDO as printf by default?

**Comment by sakumisu** [comment]
This is risc-v not arm , thanks.

**Comment by PMLSTaisen** [comment]
Don't understand, RISC-V could not support SWD? Or BL702 hardware make it impossible to use SWD? Any recommendation for my situation? I want to debug, but I already used pin for LCD.

**Comment by sakumisu** [comment]
RISC-V could not support SWD, it is arm standard.

**Comment by PMLSTaisen** [comment]
Thanks
