### ISSUE TITLE
Seems 'bl808_ipc.c' is missing

### ISSUE THREAD

**Issue by cjacker** [bouffalolab/bl_mcu_sdk#110]
There is a header file "drivers/soc/bl808/std/include/bl808_ipc.h", but no implementations for these function in sdk.

**Comment by Fishwaldo** [comment]
https://github.com/bouffalolab/bl_mcu_sdk/issues/48

**Comment by sakumisu** [comment]
I remove it, you can copy from sipeed sdk.

**Comment by cjacker** [comment]
> I remove it, you can copy from sipeed sdk.

thanks above.

I will close this issue.
