### ISSUE TITLE
BL604 support

### ISSUE THREAD

**Issue by JF002** [bouffalolab/bl_mcu_sdk#15]
Hello!

I was wondering if BL602 and BL604 are binary compatible (code that runs on the 602 runs out of the box on the 604)? Or does BL604 need additional support from bl_mcu_sdk and flash tools?

Thanks!

**Comment by sakumisu** [comment]
BL602 and BL604 have difference in pin num，others are the same. @JF002

**Comment by JF002** [comment]
Great, thanks!
