### ISSUE TITLE
BL702: compilation warnings about macro redefinitions

### ISSUE THREAD

**Issue by metro94** [bouffalolab/bl_mcu_sdk#16]
When compiling SDK with including `usb_core.h` and `bluetooth.h`, several macros are redefined:

![DJ_90HP)}0B)}}4MU XCYD0](https://user-images.githubusercontent.com/20594722/129829284-b2224cf6-53e7-41d1-a375-422209c4d53e.png)

* BIT(x): predefinition is checked in `bl_port.h`, but not in `usb_util.h`.
* ARRAY_SIZE(x): these definitions are different in `util.h` and `usbd_util.h`.

Please fix it to compile warning-free programs.

**Comment by sakumisu** [comment]
Thank you，next time will fix these.
