### ISSUE TITLE
BL602 sdk no wifi feature

### ISSUE THREAD

**Issue by Eltopinovatif** [bouffalolab/bl_mcu_sdk#20]
bl-mcu-iot I can't find how to use the wifi feature, is there not yet a wifi SDK feature for BL602 in this SDK?
Is there a bouffalolab team that can help?

**Comment by YafeiJin** [comment]
Thanks for your suggestion. While, how about switching to bl_iot_sdk, which supports WiFi feature.

**Comment by Eltopinovatif** [comment]
The bl-mcu-iot sdk developer will not add wifi features to this SDK

**Comment by thinhx2** [comment]
> The bl-mcu-iot sdk developer will not add wifi features to this SDK

Hi, seem like NDA,contracts forced they closed code of wifi module. Btw with older sdk, wifi still available 😀
