### ISSUE TITLE
Windows 7 CDC Driver

### ISSUE THREAD

**Issue by gamelaster** [bouffalolab/bl_mcu_sdk#28]
At the moment, custom USB CDC driver is required for flashing BL70X via USB on Windows 7.
It was mentioned in https://github.com/bouffalolab/bl_mcu_sdk/issues/22#issuecomment-1056040870 that Windows 7 driver should be created someday.

**Comment by gamelaster** [comment]
Hey Sakumisu, is this fixed? I am not aware there are drivers for Windows 7 ☹️

**Comment by sakumisu** [comment]
This is windows issue not us.

**Comment by sakumisu** [comment]
Only right click and update driver will be ok i think
