### ISSUE TITLE
hal_mtimer.c

### ISSUE THREAD

**Issue by alex5529** [bouffalolab/bl_mcu_sdk#30]
There is a check in mtimer_get_time_us() that makes sure you don't overflow the lower register while reading the higher register, line 97 and 99 should switch places in order to get this behaivour. This is done correctly on line 60 in the same file
    
do {
        tmpValLow = *(volatile uint32_t *)(CLIC_CTRL_ADDR + CLIC_MTIME);
        tmpValHigh = *(volatile uint32_t *)(CLIC_CTRL_ADDR + CLIC_MTIME + 4);
        tmpValHigh1 = *(volatile uint32_t *)(CLIC_CTRL_ADDR + CLIC_MTIME + 4);
    } while (tmpValHigh != tmpValHigh1);

should become

    do {
        tmpValHigh1 = *(volatile uint32_t *)(CLIC_CTRL_ADDR + CLIC_MTIME + 4);
        tmpValLow = *(volatile uint32_t *)(CLIC_CTRL_ADDR + CLIC_MTIME);
        tmpValHigh = *(volatile uint32_t *)(CLIC_CTRL_ADDR + CLIC_MTIME + 4);
    } while (tmpValHigh != tmpValHigh1);

in both bl702 and bl602 hal drivers.

**Comment by sakumisu** [comment]
Thank you for pointing our, this will be fixed later.
