### ISSUE TITLE
How to set DMA cyclic mode?

### ISSUE THREAD

**Issue by pvvx** [bouffalolab/bl_mcu_sdk#35]
In the new SDK v2.0 (lhal), there are no flags to set cyclic DMA.

Forces the use of inserts with forced direct access to registers:
```
    lli[0].nextlli = (uint32_t)&lli[0];
    putreg32(lli[0].nextlli, dma0_ch0->reg_base + DMA_CxLLI_OFFSET);
```

https://github.com/pvvx/bl702_adc_test/blob/main/src/sdk2/adc2usb/src/adc_dma.c#L246
https://github.com/pvvx/bl702_adc_test/blob/main/src/sdk2/adc2usb/src/dac_dma.c#L107

SDK v1.4.5 uses the flag `transfer_mode` in `dma_device_t `: DMA_LLI_CYCLE_MODE or DMA_LLI_ONCE_MODE

**Comment by sakumisu** [comment]
Thank you, this feature will be added next time.

**Comment by sakumisu** [comment]
You can try this patch. And `bflb_dma_channel_lli_reload` function return with `lli_count_used_offset`, then set return val into  `bflb_dma_channel_lli_link_head`

```
void bflb_dma_channel_lli_link_head(struct bflb_device_s *dev,
                                    struct bflb_dma_channel_lli_pool_s *lli_pool,
                                    uint32_t used_lli_count)
{
    uint32_t channel_base;

    channel_base = dev->reg_base;

    lli_pool[used_lli_count - 1].nextlli = (uint32_t)(uintptr_t)&lli_pool[0];

    putreg32(lli_pool[0].nextlli, channel_base + DMA_CxLLI_OFFSET);
#if defined(BL616) || defined(BL606P) || defined(BL808)
    /* clean cache, DMA does not pass through the cache */
    bflb_l1c_dcache_clean_range((uint32_t *)(uintptr_t)lli_pool, sizeof(struct bflb_dma_channel_lli_pool_s) * used_lli_count);
#endif
}
```

**Comment by sakumisue** [comment]
Done
