### ISSUE TITLE
What does "full open source" mean?

### ISSUE THREAD

**Issue by bryceschober** [bouffalolab/bl_mcu_sdk#38]
Doesn't the livpka.a blob contradict your claim that this is completely open source?

**Comment by bryceschober** [comment]
Also, it doesn't look like the toolchain is at <https://gitee.com/bouffalolab/toolchain_gcc_t-head_linux> is at all open source.

**Comment by gamelaster** [comment]
@bryceschober you can compile gcc RISC-V toolchain by yourself, and it will work just fine.

About binary blobs, RF stuff (WiFi, ZigBee, BT, Matter etc.) are closed sourced, due NDAs and various other problems. Everything else is open.
