### ISSUE TITLE
Documentation about network subsystem

### ISSUE THREAD

**Issue by mindstorm38** [bouffalolab/bl_mcu_sdk#41]
Hi, I'm wondering where to find documentation about all the network subsystem in details, I cannot find any information about Wifi/Zigbee/BT either in the reference manual or the datasheet, they are only mentioned but no register/IRQ description is available.

It seems intentional, so am I missing something in another doc?

**Comment by gamelaster** [comment]
Hi, those technologies are mostly under NDA, thus only way of getting more info is by reverse engineering.

**Comment by mindstorm38** [comment]
Wow ok this sounds a bit difficult xD Thank you anyway 👍

**Comment by gamelaster** [comment]
@mindstorm38 oh sorry! I was in assumption this is directly BL808 question, but it might be not.
About what information are you interested? If about registers and other stuff, then it is situation described in my previous message. If it is about how to get Wifi/Zigbee/BT working at all, BL60X and BL70X are supported in BL_IOT_SDK and BL_MCU_SDK, and support for BL808 is not officially released yet.

**Comment by mindstorm38** [comment]
> If about registers and other stuff, then it is situation described in my previous message. If it is about how to get Wifi/Zigbee/BT working at all, BL60X and BL70X are supported in BL_IOT_SDK and BL_MCU_SDK, and support for BL808 is not officially released yet.

Ok, I can start by looking at BL60X and BL70X to understand how they work, but without registers I will not be able to do anything I guess.

**Comment by sakumisu** [comment]
Registers are not available, all of iot business are the same, just work with applications, no think about hardware.

**Comment by mindstorm38** [comment]
I would have liked to build a custom application on that, no problem tho.
