### ISSUE TITLE
Camera support on BL808

### ISSUE THREAD

**Issue by pauljurczak** [bouffalolab/bl_mcu_sdk#43]
The front page marks cameras as not supported. There are several low cost boards with MIPI camera interface, e.g. Sipeed M1s Dock: https://wiki.sipeed.com/hardware/en/maix/m1s/m1s_dock.html. 

Is there any chance to get cameras supported on BL808?

**Comment by sakumisu** [comment]
DVP interface will release, if you use mipi interface, you can refer to sipeed sdk.

**Comment by pauljurczak** [comment]
Thank you.

**Comment by sakumisu** [comment]
Dvp has supported.
