### ISSUE TITLE
Camera, MJPEG, H264 documentation

### ISSUE THREAD

**Issue by mindstorm38** [bouffalolab/bl_mcu_sdk#50]
Hi! 

I feel like there is a little asymmetry in the level of documentation between Reference Manual and SDK, regarding interactions between Camera, MJPEG and H265 modules. 

For example, the module that seems responsible for accepting CSI in DVP module (using the CAM_FRONT registers) is not documented, while CAM registers are. In general these modules are implemented and partially documented but lacks of information about interactions between all of them, especially CSI/CAM, CAM/MJPEG with hardware mode. It would be really helpful if these fields were more documented.

Thank you anyway, this is hard but good learning for me :)

**Comment by mindstorm38** [comment]
In the root README, MJPEG is marked supported, if it's not the case it should be fixed I think, and H264 isn't in the table.

**Comment by sakumisu** [comment]
Mjpeg is supported. and have case in bl702/bl616/bl808, so why it should be fixed?

**Comment by sakumisu** [comment]
We will not release H264 in our sdk not, you can refer to sipeed sdk.

**Comment by mindstorm38** [comment]
> Mjpeg is supported. and have case in bl702/bl616/bl808, so why it should be fixed?

This was in response to @gamelaster , I thought MJPEG wasn't supported as he said...

> We will not release H264 and CSI in our sdk now, you can refer to sipeed sdk.We only provide common peripherals.

Ok, no problem I'll look at their SDK

**Comment by sakumisu** [comment]
CAM with dvp and mjpeg are supported in BL702/BL616/BL808. If you want to use h264 and csi, just copy drivers from sipeed sdk to mcu sdk, we do not use now so removed them not compile them.

**Comment by sakumisu** [comment]
Its codestyle need to be refactored. So i removed them.
