### ISSUE TITLE
DRAM 

### ISSUE THREAD

**Issue by Fishwaldo** [bouffalolab/bl_mcu_sdk#52]
Hi,
Just wondering why we are only allocating 64K DRAM in the D0 linker script when we have 512K?

https://github.com/bouffalolab/bl_mcu_sdk/blob/a574195a4b3399341794971a2ab4b8b17f4b70d7/bsp/board/bl808dk/bl808_flash_d0.ld#L29

**Comment by sakumisu** [comment]
Others for media peripherals.
