### ISSUE TITLE
BL808 D0 does not work with IPC_SYNC

### ISSUE THREAD

**Issue by kaofishy** [bouffalolab/bl_mcu_sdk#64]
On Sipeed M1S Dock, when compiling for the BL808 D0 CPU none of the examples worked, JTAG revealed that the core was stuck in this IPC_SYNC loop: https://github.com/bouffalolab/bl_mcu_sdk/blob/9e189b69cbc0a75ffa170f600a28820848d56432/drivers/soc/bl808/std/startup/d0/system_bl808.c#L11-L21

Commenting out the loop resolves the issue.

**Comment by kaofishy** [comment]
BTW what is special about where IPC_SYNC_ADDR1 and IPC_SYNC_ADDR2 are located (0x40000000)? The linker script labels it `xram` so is it just regular SRAM?

**Comment by sakumisu** [comment]
Update code.

**Comment by kaofishy** [comment]
@sakumisu updated to the latest git and still doesn't work without commenting out the IPC_SYNC loop. 

This is my DevCube settings btw if that matters:
![image](https://user-images.githubusercontent.com/23109321/213062233-cd2c98db-c67a-40ba-af98-fd76b7b7626b.png)

**Comment by sakumisu** [comment]
please chip erase

**Comment by sakumisu** [comment]
I test it is ok in M1S

**Comment by sakumisu** [comment]
I test it is ok in M1S

**Comment by kaofishy** [comment]
Tried it on two different M1s, clean repo, with chip erase enabled in DevCube, still does not boot if I don't comment out the loop. Maybe there is a timing issue that doesn't show up on all hardware?

**Comment by sakumisu** [comment]
Sorry, i dont know. Ours here are all ok.

**Comment by sakumisu** [comment]
Just now.

```
Build:11:27:17,Jan 18 2023
Copyright (c) 2022 Bouffalolab team
dynamic memory init success,heap size = 59 Kbyte 
sig1:ffff32ff
sig2:0000ffff
cgen1:9f7ffffd
[F][MAIN] hello world d0
[E][MAIN] hello world d0
[W][MAIN] hello world d0
[I][MAIN] hello world d0
[F][MAIN] hello world d0
[E][MAIN] hello world d0
[W][MAIN] hello world d0
[I][MAIN] hello world d0
[F][MAIN] hello world d0
[E][MAIN] hello world d0
[W][MAIN] hello world d0
[I][MAIN] hello world d0

```

**Comment by sakumisu** [comment]
Update code and have a try.

**Comment by kaofishy** [comment]
@sakumisu working perfectly now

**Comment by CrazyShout** [comment]
@kaofishy Hello, I have also encountered such a problem now. Did you solve the problem just by updating the code? What are your specific steps.Thank you!
