### ISSUE TITLE
Controlling LP

### ISSUE THREAD

**Issue by alexhorner** [bouffalolab/bl_mcu_sdk#66]
Hi there,

Please can you provide the minimum information we require to let LP run code? We would like to know where in flash LP starts execution,

Thanks

**Comment by kaofishy** [comment]
The reset vectors, at least after the Bootrom, appear to all be 0x58000000 but the flash controller remaps this address space for each CPU to different parts of the flash. But yeah it would be nice if the mechanism is documented.

**Comment by sakumisu** [comment]
LP will support later.
