### ISSUE TITLE
Please publish openocd source code

### ISSUE THREAD

**Issue by aw** [bouffalolab/bl_mcu_sdk#70]
Hello,

There is an `openocd` binary [located here](https://github.com/bouffalolab/bl_mcu_sdk/tree/master/tools/openocd) and the source code is not available. Can you please publish the full sources along with steps and changes required to build this specific version of openocd?

Thank you.

**Comment by sakumisu** [comment]
You can build by yourself from openocd official repo.

**Comment by sakumisu** [comment]
It is just copied from there.

**Comment by gamelaster** [comment]
I can confirm that openocd from repositories works just fine, no changes needed.

**Comment by aw** [comment]
> I can confirm that openocd from repositories works just fine, no changes needed.

OK thank you!
