### ISSUE TITLE
Explaining UART clocks

### ISSUE THREAD

**Issue by mindstorm38** [bouffalolab/bl_mcu_sdk#71]
Hi, I'm trying to understand how UART clock should be configured.

The reference manual clock diagram just shows one demux to select between `xclk`, `muxpll_160m_clk` and `mcu_bclk` and a divider:

![image](https://user-images.githubusercontent.com/17071361/213911575-c64bdd6c-ca17-4b73-86ad-171d79db493d.png)

The issue is that in the board support code for peripheral clock initialization, we first see a clock enable thing, which is not mentioned in the diagram (at least now for each UART separately, but it's not my real problem because it's straightforward to understand):
https://github.com/bouffalolab/bl_mcu_sdk/blob/607c24d7fe4ae0cea6ddda7e660c6caccbf3e23d/bsp/board/bl808dk/board.c#L51

What I don't understand is the following code:
https://github.com/bouffalolab/bl_mcu_sdk/blob/607c24d7fe4ae0cea6ddda7e660c6caccbf3e23d/bsp/board/bl808dk/board.c#L63-L64

Why there are two demux selector registers and two divider ones (one in HBN and another in MM_GLB)? Also, there exist a `GLB_Set_DSP_UART1_CLK` function for UART1 but not for UART2, in this case how should we configure UART2?

**Comment by sakumisu** [comment]
Only UART3 use `GLB_Set_DSP_UART0_CLK` ,uart0 ~2 use ` GLB_Set_UART_CLK(ENABLE, HBN_UART_CLK_XCLK, 0); 
`

**Comment by mindstorm38** [comment]
So the naming is confusing? And what about `GLB_Set_DSP_UART1_CLK` ?

**Comment by sakumisu** [comment]
Just ignore.

**Comment by sakumisu** [comment]
UART3 is d0 first uart, named uart0 ,no confuse.

**Comment by mindstorm38** [comment]
Ok, ty
