### ISSUE TITLE
Can't build BL616/BL808

### ISSUE THREAD

**Issue by clem844** [bouffalolab/bl_mcu_sdk#76]
For BL616 chip, when building any example with `make CHIP=bl616 BOARD=bl616dk` there is the following error:
``` shell
cc1: error: unknown cpu 'e907' for '-mtune'
```
aslo tried with BL808 `make CHIP=bl808 BOARD=bl808dk CPU_ID=m0` with same error.

**Comment by Fishwaldo** [comment]
Looks like you don’t have the right compiler installed in your path.

**Comment by gamelaster** [comment]
As @Fishwaldo says, wrong compiler. I compiled several images just fine for BL616.

**Comment by clem844** [comment]
My mistake, I had another RISC-V toolchain in my path and it was using this one instead. 

Thanks!
