### ISSUE TITLE
printf support

### ISSUE THREAD

**Issue by Fishwaldo** [bouffalolab/bl_mcu_sdk#86]
Hi,
any plans around refactoring printf support? currently we can only specify UART peripherals as console with ```bflb_uart_set_console(struct bflb_device_s *dev)``` but I would like to use for example, cdc-acm or TCP terminals as console.

(I see something was attempted in the vlibc implementation, but that was not completed either)

Would you accept a PR to allow console to be redirected to function pointers instead?

**Comment by sakumisu** [comment]
Later use c99 or posix instead.
