### ISSUE TITLE
[Feature Request]: Please add sipeed RV BL702 board as mcu target to run examples

### ISSUE THREAD

**Issue by cooldome** [bouffalolab/bl_mcu_sdk#9]
Please add  "sipeed RV plus Debugger BL702" board support as mcu target.
It would allow for the favorable setup with two sipeed BL702 boards: one as mcu and one as debugger.
Also Iam looking for the way to connect two boards as JTAG debugger for one another. If you know the correct wiring please let me know.

Thank you

**Comment by sakumisu** [comment]
bl702 default JTAG pin are list：TMS(GPIO0)、TDI(GPIO1)、TCK(GPIO2)、TDO(GPIO9),so if you wants to connect two boars as JTAG debugger for one another,you should connect one TMS、TDI、TCK with another TDI、TDO、TMS，then there is TDO with TCK left, TDO is GPIO9,and is led0 on rv debugger ,its location is align with TMS pin on board,so you need to solder a wire to the resistor right on the right side of the led and link this pin to JTAG TCK. Finally ,you can debug with two boards.

**Comment by strongwong** [comment]
https://bbs.bouffalolab.com/d/61-rvddebuggeropenocdbl706/7
There are pictures in this post to illustrate, you can refer to it.
