### ISSUE TITLE
LP Linker Script

### ISSUE THREAD

**Issue by Fishwaldo** [bouffalolab/bl_mcu_sdk#95]
Hi,
Just want to confirm that the Linker Script for LP allocates memory that is overlapping with the M0 core?

seems ram_memory for LP starts 16K (0x22034000) into the same region as M0 (0x62030000)? (taking into account cached/uncached regions)

Wouldn't it have been better to place at the top of WRAM instead of the middle as it restricts what M0 can use

**Comment by sakumisu** [comment]
Ignore LP code, thanks.
